---
- name: Add APT repository
  hosts: all
  become: true

  tasks:
### PPA
  - name: Deadbeef key
    apt_key:
      id: 8529B1E0F8BF7F65C12FABB0A4BCBD87CEF9E52D
      keyserver: keyserver.ubuntu.com
  - name: Deadbeef
    apt_repository:
      repo: deb http://ppa.launchpad.net/alex-p/deadbeef/ubuntu focal main 

  - name: Telegram key
    apt_key:
      id: A3D8A366869FE2DC5FFD79C36A9653F936FD5529
      keyserver: keyserver.ubuntu.com
  - name: Telegram
    apt_repository:
      repo: deb http://ppa.launchpad.net/atareao/telegram/ubuntu focal main 

### Other
  - name: Atom key
    apt_key:
      url: https://packagecloud.io/AtomEditor/atom/gpgkey
  - name: Atom
    apt_repository:
      repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main

  - name: Brave key
    apt_key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
  - name: Brave
    apt_repository:
      repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main

  - name: Opera key
    apt_key:
      url: https://deb.opera.com/archive.key
  - name: Opera
    apt_repository:
      repo: deb https://deb.opera.com/opera-stable/ stable non-free

  - name: Palemoon key
    apt_key:
      url: https://download.opensuse.org/repositories/home:stevenpusser/xUbuntu_20.04/Release.key
  - name: Palemoon
    apt_repository:
      repo: deb http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_20.04/ /

  - name: Skype key
    apt_key:
      url: https://repo.skype.com/data/SKYPE-GPG-KEY
  - name: Skype
    apt_repository:
      repo: deb [arch=amd64] https://repo.skype.com/deb stable main

  - name: Vivaldi key
    apt_key:
      url: https://repo.vivaldi.com/archive/linux_signing_key.pub
  - name: Vivaldi
    apt_repository:
      repo: deb http://repo.vivaldi.com/stable/deb/ stable main

  # - name: VSCode key
  #   apt_key:
  #     url: https://packages.microsoft.com/keys/microsoft.asc
  # - name: VSCode
  #   apt_repository:
  #     repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

  - name: VSCodium key
    apt_key:
      url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
  - name: VSCodium
    apt_repository:
      repo: deb https://download.vscodium.com/debs vscodium main

  - name: Wire-desktop key
    apt_key:
      url: https://wire-app.wire.com/linux/releases.key
  - name: Wire-desktop
    apt_repository:
      repo: deb [arch=amd64] https://wire-app.wire.com/linux/debian stable main
