---
- name: Copnfigure k3s for user
  hosts: all

  vars:
  - user_homedir: "{{ ansible_env.HOME }}"
  - user_name: "{{ ansible_env.USER }}"

  tasks:
  - name: Create directory for user config
    file:
      path: "{{ user_homedir }}/.kube"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: Setup kubeconfig for user
    copy:
      src: /etc/rancher/k3s/k3s.yaml
      dest: "{{ user_homedir }}/.kube/config"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0600'
      remote_src: yes
    become: yes

  - name: Add config path to ~/.bashrc
    blockinfile:
      path: "{{ user_homedir }}/.bashrc"
      block: |
        export KUBECONFIG="{{ user_homedir }}/.kube/config"

