---
- name: Enable beep
  hosts: all
  become: true

  tasks:
  - name: Enable beep
    lineinfile:
      path: /etc/modprobe.d/blacklist.conf
      regexp: 'blacklist pcspkr'
      line: '# blacklist pcspkr'


