---
- name: Install Terraform
  hosts: all
  become: true

  vars:
    terra_version: 1.0.11

  tasks:
  - name: Download terraform
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terra_version }}/terraform_{{ terra_version }}_linux_amd64.zip
      dest: /tmp/

  - name: Extract archive
    unarchive:
      src: /tmp/terraform_{{ terra_version }}_linux_amd64.zip
      dest: /usr/local/bin/
      mode: a+x
      remote_src: yes

  - name: Edit qemu.conf (Or there will be Permission denied Error)
    lineinfile:
      path: /etc/libvirt/qemu.conf
      regexp: 'security_driver = "'
      line: 'security_driver = "none"'
    notify: restart_libvirt

  handlers:
  - name: restart_libvirt
    service:
      name: libvirtd
      state: restarted
      enabled: yes