---
- name: Install OpenProject
  hosts: all
  become: true

  tasks:
  - name: Add apt repo
    apt_key:
      url: https://dl.packager.io/srv/opf/openproject/key
  - apt_repository:
      repo: deb https://dl.packager.io/srv/deb/opf/openproject/stable/11/ubuntu 20.04 main

  - name: Install
    package: name={{ item }} state=present update_cache=yes
    with_items:
    - openproject