---
- name: Install Jenkins
  hosts: all
  become: true

  tasks:
  - name: Add apt repo
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
  - apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/

  - name: Install
    package: name={{ item }} state=present update_cache=yes
    with_items:
    - default-jre
    - jenkins

  - name: Enable and start service
    service:
      name: jenkins
      state: restarted
      enabled: yes