---
- name: Install and configure tmux for user
  hosts: all

  vars:
  - user_homedir: "{{ ansible_env.HOME }}"
  - tm_color: colour166 #orange

  tasks:
  - name: Install tmux
    package: 
      name: tmux
      state: present
    become: true

  - name: Copy .tmux.conf
    template:
      src: ./.tmux.conf.j2
      dest: "{{ user_homedir }}/.tmux.conf"

  - name: Create directory
    file:
      path: "{{ user_homedir }}/.tmux/plugins/tpm"
      state: directory

  - name: Clone plugin manager
    git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: "{{ user_homedir }}/.tmux/plugins/tpm"

  - name: Install plugins
    shell: "{{ user_homedir }}/.tmux/plugins/tpm/bin/install_plugins"
    ignore_errors: true
